# Generated by Django 5.0.2 on 2024-03-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_checkstudents_accessstudents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="max_users",
        ),
        migrations.RemoveField(
            model_name="group",
            name="min_users",
        ),
        migrations.AddField(
            model_name="product",
            name="max_users",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_users",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
