# Generated by Django 5.0.2 on 2024-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_group_max_users_remove_group_min_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_data",
            field=models.DateTimeField(null=True),
        ),
    ]
