# Generated by Django 5.0.2 on 2024-03-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_created_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created_data",
            new_name="date_start",
        ),
    ]
