# Generated by Django 5.0.2 on 2024-03-01 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_created_data_product_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 1, 22, 50, 6, 557019, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
