# Generated by Django 5.0.2 on 2024-03-02 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_accessstudents_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="start_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 2, 20, 35, 33, 335698, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
