# Generated by Django 5.0.2 on 2024-03-02 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_group_name_alter_product_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(default="default_group the objects", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="date_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 2, 21, 20, 37, 811181, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
