# Generated by Django 5.0.2 on 2024-03-03 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_product_date_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessstudents",
            options={
                "verbose_name": "Новый доступ",
                "verbose_name_plural": "Доступы пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "verbose_name": "Добавить группы",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "Добавить урок"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Добавить продукт",
                "verbose_name_plural": "Создать продукт",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Добавить пользователя",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="date_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 3, 4, 36, 24, 897056, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
