# Generated by Django 5.0.2 on 2024-06-15 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_accessstudents_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_start",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 15, 16, 33, 58, 806751, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
